spring:
  application:
    name: springAI
#  profiles:
#    active: local
  ai:
    dashscope:
      api-key: "sk-80326a6dd48f443b83e4461950ca4db5"
      chat:
        options:
          model: qwen-max
  logging:
    level:
      org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.springai
knife4j:
  enable: true
  setting:
    language: zh_cn

server:
  port: 8123
  servlet:
    context-path: /api
search-api:
  api-key: xpQ7GQA3r8mDfaztiG1hQCpQ







